server:
  port: 8082
host: 'localhost'
# This is keycloak from docker-compose.yml
keycloak.uri: 'http://${host}:8080'
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            check-token-uri: '${keycloak.uri}/auth/realms/alfa-skillbox-https/protocol/openid-connect/token/introspect'
            token-uri: '${keycloak.uri}/auth/realms/alfa-skillbox-https/protocol/openid-connect/token'
        registration:
          gateway:
            name: "gateway"
            registrationId: 'gateway'
            provider: 'keycloak'
            client-id: 'gateway'
            client-secret: 'CeCdMsVRRWjUKobxGtvH1mnc0PR08esW'
            authorization-grant-type: 'client_credentials'
logging:
  level:
    org.springframework: INFO

rest:
  client:
    httpsServer:
      urlSave: 'http://${host}:8081/json/save'
      urlFind: 'http://${host}:8081/json/find'