version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak-local
    networks:
      - common
    environment:
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_PASSWORD: 'admin'
      DB_VENDOR: 'h2'
      KEYCLOAK_LOGLEVEL: "INFO"
      KEYCLOAK_IMPORT: "/tmp/example-realm.json"
    volumes:
      - ./imports/keycloak/realm-config.json:/tmp/example-realm.json
    ports:
      - "8080:8080"

  resource-server:
    image: "ru.alfabank.skillbox.examples/resource-server:0.0.1-snapshot"
    container_name: resource-server
    networks:
      - common
    environment:
      KEYSTORE_PATH: '/etc/https/keystore.jks'
      KEYSTORE_PASSWORD: 'resource-server-password'
      KEYSTORE_TYPE: 'JKS'
      SPRING_PROFILES_ACIVE: local
      JAVA_OPTS: "
            -Djavax.net.ssl.trustStore=/etc/https/truststore.jks
            -Djavax.net.ssl.trustStorePassword=resource-server-password
            -Djavax.net.ssl.trustStoreType=JKS
            -Djavax.net.debug=all"
    volumes:
      - ./imports/resource-server/truststore.jks:/etc/https/truststore.jks
      - ./imports/resource-server/keystore.jks:/etc/https/keystore.jks
      - ./imports/resource-server/rootCA.cert.pem:/root/.postgresql/root.crt
    ports:
      - "8081:8081"

  gateway:
    image: "ru.alfabank.skillbox.examples/gateway:0.0.1-snapshot"
    container_name: gateway
    networks:
      - common
    environment:
      SPRING_PROFILES_ACIVE: local
      JAVA_OPTS: "
            -Djavax.net.ssl.trustStore=/etc/https/truststore.jks
            -Djavax.net.ssl.trustStorePassword=gateway-password
            -Djavax.net.ssl.trustStoreType=JKS
            -Djavax.net.debug=all"
    volumes:
      - ./imports/gateway/truststore.jks:/etc/https/truststore.jks
    ports:
      - "8082:8082"

  postgre:
    image: 'postgres:13.5'
    restart: always
    networks:
      - common
    environment:
      POSTGRES_DB: alfa_skillbox_https_resource_server_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data.postgre:

networks:
  common: