version: '3.7'
services:
    keycloak:
        image: jboss/keycloak:16.1.1
        container_name: keycloak-local
        environment:
            KEYCLOAK_USER: 'admin'
            KEYCLOAK_PASSWORD: 'admin'
            DB_VENDOR: 'h2'
            SERVER_KEYSTORE_PASSWORD: 'qwerty'
#            PROXY_ADDRESS_FORWARDING: 'true'
            KEYCLOAK_IMPORT: "/tmp/example-realm.json"
        volumes:
            - ./imports/keycloak/localhost.keycloak.crt:/etc/x509/https/tls.crt
            - ./imports/keycloak/localhost.keycloak.key.pem:/etc/x509/https/tls.key
            - ./imports/keycloak/realm-config.json:/tmp/example-realm.json
        ports:
            - "8443:8443"

    postgre:
        image: 'postgres:11'
        restart: always
        networks:
          - bd
        environment:
            POSTGRES_DB: alfa_skillbox_https_resource_server_db
            POSTGRES_USER: postgre
            POSTGRES_PASSWORD: postgre
        volumes:
            - ./imports/postgre/init/init-db-schema.sql://docker-entrypoint-initdb.d/init-db-schema.sql
            - ./data/postgre:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    adminer:
        image: adminer
        restart: always
        networks:
            - bd
        ports:
            - 9999:8080

volumes:
    data.postgre:

networks:
    bd: