# keycloak uri из docker-compose.yml
keycloak.uri: 'http://localhost:8888'
spring:
  datasource:
    name: "alfa-skillbox-https-resource-server"
    url: "jdbc:postgresql://localhost:5432/alfa_skillbox_https_resource_server_db"
    username: 'postgre'
    password: 'postgre'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.dialect: 'org.hibernate.dialect.PostgreSQL95Dialect'
      hibernate.current_session_context_class: 'org.springframework.orm.hibernate5.SpringSessionContext'
      hibernate.connection.characterEncoding: "UTF-8"
      hibernate.connection.charSet: "UTF-8"
      hibernate.temp.use_jdbc_metadata_defaults: "true"
      hibernate.physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  security:
    oauth2:
      resourceserver:
        jwt:
          #TODO поменять на валидацию через кейклок
          check-token-uri: '${uri.balancer.keycloak}/auth/realms/azon-minio-local/protocol/openid-connect/token/introspect'
#          jwkSetUri: '${keycloak.uri}/auth/realms/alfa-skillbox/protocol/openid-connect/certs'
logging:
  level:
    org.springfaramework: DEBUG
    org.springfaramework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.desriptor.sql.BasicBinder: TRACE

feign:
  client:
    config:
      rest-json-validation:
        connectTimeout: 2000
        readTimeout: 2000
  clients:
    rest-json-validation:
      retryer:
        period: 1000
        maxPeriod: 1000
      name: 'rest-json-validation'
      url: 'https://assertible.com'
      path: 'json'