spring:
  application:
    name: alfa-skillbox-https-resource-server
  profiles:
    active: local

# -Djavax.net.ssl.trustStore=/Users/aleksandriv/Projects/Alfa/skillbox/https/https-server/src/main/resources/localhost.server.truststore.jks
# -Djavax.net.ssl.trustStorePassword=qwerty -Djavax.net.ssl.trustStoreType=JKS
# -Djavax.net.ssl.keyStore=/Users/aleksandriv/Projects/Alfa/skillbox/https/docker/internalca/server-java/localhost.server.keystore
# -Djavax.net.ssl.keyStorePassword=https_server_password -Djavax.net.ssl.keyStoreType=PKCS12 -Djavax.net.debug=SSH
# enable/disable https
server.ssl.enabled: true
# keystore format
server.ssl.key-store-type: JKS
# keystore location
#server.ssl.key-store: classpath:localhost.server.keystore
server.ssl.key-store: classpath:localhost.server.keystore.jks
# keystore password
server.ssl.key-store-password: serverpass
# SSL protocol to use
server.ssl.protocol: TLS
# Enabled SSL protocols
server.ssl.enabled-protocols: TLSv1.2
#trust store location
server.ssl.trust-store: classpath:localhost.server.truststore.jks
#server.ssl.trust-store: classpath:localhost.server.truststore.p12
#trust store password
server.ssl.trust-store-password: qwerty
server.ssl.trust-store-type: JKS