# VM options -Djavax.net.ssl.trustStore=/Users/aleksandriv/Projects/Alfa/skillbox/https/docker/internalca/client-java/localhost.client.truststore.jks -Djavax.net.ssl.trustStorePassword=asdfgh -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.debug=SSL,handshake
spring:
  application:
    name: alfa-skillbox-https-client
  profiles:
    active: local