CREATE SCHEMA IF NOT EXISTS https_server_schema AUTHORIZATION postgre;

GRANT ALL ON SCHEMA https_server_schema TO postgre;

ALTER DEFAULT PRIVILEGES IN SCHEMA https_server_schema
GRANT ALL ON TABLES TO postgre WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA https_server_schema
GRANT SELECT, USAGE ON SEQUENCES TO postgre WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA https_server_schema
GRANT EXECUTE ON FUNCTIONS TO postgre WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA https_server_schema
GRANT USAGE ON TYPES TO postgre WITH GRANT OPTION;

-- Table: users

CREATE TABLE IF NOT EXISTS https_server_schema.jsons (
  id bigserial NOT NULL UNIQUE PRIMARY KEY,
  json jsonb NOT NULL
);

ALTER TABLE https_server_schema.jsons
    OWNER to postgre;